routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',['uses'=>'HomeController@home'])->name('home');


Route::get('/roles/all',['uses'=>'Roletypecontroller@getAllRoles']);
Route::resource('roles', 'Roletypecontroller');

Route::get('/producer/all',['uses'=>'ProducerController@getProducersAll']);
Route::resource('producer', 'ProducerController');

Route::get('/genre/all',['uses'=>'GenreController@getAllGenre']);
Route::resource('genre', 'GenreController');

Route::get('/actor/all',['uses'=>'ActorController@getActorsAll']);
Route::resource('actor', 'ActorController');

Route::post('/movie/{id}/update',['uses'=>'MovieController@update']);
Route::get('/movie/getrole-actor',['uses'=>'MovieController@getRoleActor']);
Route::get('/movie/all',['uses'=>'MovieController@getAllMovie']);
Route::resource('movie', 'MovieController');

resources/views/layouts/head.blade.php
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
<style type="text/css">
    .error {
  color: #F00;
  background-color: #FFF;
}

    </style>
<script
    src=//code.jquery.com/jquery-3.5.1.min.js
    integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
    crossorigin=anonymous></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.15.0/additional-methods.js"></script>
    <script src="https://code.jquery.com/jquery-migrate-3.0.0.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
<link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/themes/smoothness/jquery-ui.min.css" />
{{-- <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script> --}}
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.6.0/umd/popper.min.js" integrity="sha512-BmM0/BQlqh02wuK5Gz9yrbe7VyIVwOzD1o40yi1IsTjriX/NGF37NyXHfmFzIlMmoSIBXgqDiG1VNU6kB5dBbA==" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/4.4.0/bootbox.min.js" integrity="sha512-8NOmlkzoskIBni4iy5onHC57Mndt17mZgWkYJvxe5jwBJu3spYIRSjTkYJ9OLNS9Min+bsSqbDfGaoejWxyFiw==" crossorigin="anonymous"></script>
<script>
    $( function() {
      $( "#sortable" ).sortable();
      $( "#sortable" ).disableSelection();
    } );



  $( function() {
    $( "#resizable" ).resizable();
  } );
  </script>
    </script>
{{-- <script type=text/javascript src="{{ asset('js/actor.js') }}"></script> --}}

resources/views/layouts/master.blade.php
<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="csrf-token" content="{{ csrf_token() }}" />
        <title>@yield('title')</title>
        @include('layouts.head')
        <script>var base_url="{{ asset('/') }}";</script>
        @yield('additional_sripts');
    </head>
    <body>
        {{-- @include('layouts.navbar') --}}
        <div class="container">
            @include('layouts.navbar')
        </div>
        @yield('body')
        @yield('script')
    </body>
</html>

resources/views/layouts/navbar.blade.php
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">{{ config('app.name') }}</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{{ route('home') }}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ route('movie.index') }}">Movies</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ route('actor.index') }}">Actors</a>
        </li>
        <div class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Others</a>
            <div class="dropdown-menu">
                <a href="{{ route('genre.index') }}" class="dropdown-item">Genre</a>
                <a href="{{ route('producer.index') }}" class="dropdown-item">Producers</a>
                <a href="{{ route('roles.index') }}" class="dropdown-item">RoleTypes</a>
            </div>
        </div>
      </ul>
    </div>
  </div>
</nav>